ALTER TABLE the_monkeys_user 
ALTER COLUMN country_code SET DEFAULT NULL, 
ALTER COLUMN mobile_no SET DEFAULT NULL,
ALTER COLUMN about SET DEFAULT NULL,
ALTER COLUMN instagram SET DEFAULT NULL,
ALTER COLUMN twitter SET DEFAULT NULL;
