// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: apis/interservice/blogs/blogs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetUserDeactivatedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SetUserDeactivatedReq) Reset() {
	*x = SetUserDeactivatedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_interservice_blogs_blogs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserDeactivatedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserDeactivatedReq) ProtoMessage() {}

func (x *SetUserDeactivatedReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_interservice_blogs_blogs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserDeactivatedReq.ProtoReflect.Descriptor instead.
func (*SetUserDeactivatedReq) Descriptor() ([]byte, []int) {
	return file_apis_interservice_blogs_blogs_proto_rawDescGZIP(), []int{0}
}

func (x *SetUserDeactivatedReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SetUserDeactivatedRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SetUserDeactivatedRes) Reset() {
	*x = SetUserDeactivatedRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_interservice_blogs_blogs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserDeactivatedRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserDeactivatedRes) ProtoMessage() {}

func (x *SetUserDeactivatedRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_interservice_blogs_blogs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserDeactivatedRes.ProtoReflect.Descriptor instead.
func (*SetUserDeactivatedRes) Descriptor() ([]byte, []int) {
	return file_apis_interservice_blogs_blogs_proto_rawDescGZIP(), []int{1}
}

func (x *SetUserDeactivatedRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SetUserDeactivatedRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SetUserDeactivatedRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_apis_interservice_blogs_blogs_proto protoreflect.FileDescriptor

var file_apis_interservice_blogs_blogs_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x2d, 0x0a, 0x15, 0x53,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x5f, 0x0a, 0x15, 0x53, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x5f, 0x0a, 0x0b, 0x42,
	0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x12, 0x53, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c,
	0x2e, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apis_interservice_blogs_blogs_proto_rawDescOnce sync.Once
	file_apis_interservice_blogs_blogs_proto_rawDescData = file_apis_interservice_blogs_blogs_proto_rawDesc
)

func file_apis_interservice_blogs_blogs_proto_rawDescGZIP() []byte {
	file_apis_interservice_blogs_blogs_proto_rawDescOnce.Do(func() {
		file_apis_interservice_blogs_blogs_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_interservice_blogs_blogs_proto_rawDescData)
	})
	return file_apis_interservice_blogs_blogs_proto_rawDescData
}

var file_apis_interservice_blogs_blogs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apis_interservice_blogs_blogs_proto_goTypes = []interface{}{
	(*SetUserDeactivatedReq)(nil), // 0: auth.SetUserDeactivatedReq
	(*SetUserDeactivatedRes)(nil), // 1: auth.SetUserDeactivatedRes
}
var file_apis_interservice_blogs_blogs_proto_depIdxs = []int32{
	0, // 0: auth.BlogService.SetUserDeactivated:input_type -> auth.SetUserDeactivatedReq
	1, // 1: auth.BlogService.SetUserDeactivated:output_type -> auth.SetUserDeactivatedRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apis_interservice_blogs_blogs_proto_init() }
func file_apis_interservice_blogs_blogs_proto_init() {
	if File_apis_interservice_blogs_blogs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_interservice_blogs_blogs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserDeactivatedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_interservice_blogs_blogs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserDeactivatedRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_interservice_blogs_blogs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_interservice_blogs_blogs_proto_goTypes,
		DependencyIndexes: file_apis_interservice_blogs_blogs_proto_depIdxs,
		MessageInfos:      file_apis_interservice_blogs_blogs_proto_msgTypes,
	}.Build()
	File_apis_interservice_blogs_blogs_proto = out.File
	file_apis_interservice_blogs_blogs_proto_rawDesc = nil
	file_apis_interservice_blogs_blogs_proto_goTypes = nil
	file_apis_interservice_blogs_blogs_proto_depIdxs = nil
}
