// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: services/blogsandposts_service/blog_service/pb/blogsandposts.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlogsAndPostServiceClient is the client API for BlogsAndPostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogsAndPostServiceClient interface {
	CreateABlog(ctx context.Context, in *CreateBlogRequest, opts ...grpc.CallOption) (*CreateBlogResponse, error)
	Get100Blogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (BlogsAndPostService_Get100BlogsClient, error)
}

type blogsAndPostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogsAndPostServiceClient(cc grpc.ClientConnInterface) BlogsAndPostServiceClient {
	return &blogsAndPostServiceClient{cc}
}

func (c *blogsAndPostServiceClient) CreateABlog(ctx context.Context, in *CreateBlogRequest, opts ...grpc.CallOption) (*CreateBlogResponse, error) {
	out := new(CreateBlogResponse)
	err := c.cc.Invoke(ctx, "/auth.BlogsAndPostService/CreateABlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogsAndPostServiceClient) Get100Blogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (BlogsAndPostService_Get100BlogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &BlogsAndPostService_ServiceDesc.Streams[0], "/auth.BlogsAndPostService/Get100Blogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &blogsAndPostServiceGet100BlogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlogsAndPostService_Get100BlogsClient interface {
	Recv() (*GetBlogsResponse, error)
	grpc.ClientStream
}

type blogsAndPostServiceGet100BlogsClient struct {
	grpc.ClientStream
}

func (x *blogsAndPostServiceGet100BlogsClient) Recv() (*GetBlogsResponse, error) {
	m := new(GetBlogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlogsAndPostServiceServer is the server API for BlogsAndPostService service.
// All implementations must embed UnimplementedBlogsAndPostServiceServer
// for forward compatibility
type BlogsAndPostServiceServer interface {
	CreateABlog(context.Context, *CreateBlogRequest) (*CreateBlogResponse, error)
	Get100Blogs(*emptypb.Empty, BlogsAndPostService_Get100BlogsServer) error
	mustEmbedUnimplementedBlogsAndPostServiceServer()
}

// UnimplementedBlogsAndPostServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBlogsAndPostServiceServer struct {
}

func (UnimplementedBlogsAndPostServiceServer) CreateABlog(context.Context, *CreateBlogRequest) (*CreateBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateABlog not implemented")
}
func (UnimplementedBlogsAndPostServiceServer) Get100Blogs(*emptypb.Empty, BlogsAndPostService_Get100BlogsServer) error {
	return status.Errorf(codes.Unimplemented, "method Get100Blogs not implemented")
}
func (UnimplementedBlogsAndPostServiceServer) mustEmbedUnimplementedBlogsAndPostServiceServer() {}

// UnsafeBlogsAndPostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogsAndPostServiceServer will
// result in compilation errors.
type UnsafeBlogsAndPostServiceServer interface {
	mustEmbedUnimplementedBlogsAndPostServiceServer()
}

func RegisterBlogsAndPostServiceServer(s grpc.ServiceRegistrar, srv BlogsAndPostServiceServer) {
	s.RegisterService(&BlogsAndPostService_ServiceDesc, srv)
}

func _BlogsAndPostService_CreateABlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsAndPostServiceServer).CreateABlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.BlogsAndPostService/CreateABlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsAndPostServiceServer).CreateABlog(ctx, req.(*CreateBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogsAndPostService_Get100Blogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlogsAndPostServiceServer).Get100Blogs(m, &blogsAndPostServiceGet100BlogsServer{stream})
}

type BlogsAndPostService_Get100BlogsServer interface {
	Send(*GetBlogsResponse) error
	grpc.ServerStream
}

type blogsAndPostServiceGet100BlogsServer struct {
	grpc.ServerStream
}

func (x *blogsAndPostServiceGet100BlogsServer) Send(m *GetBlogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

// BlogsAndPostService_ServiceDesc is the grpc.ServiceDesc for BlogsAndPostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlogsAndPostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.BlogsAndPostService",
	HandlerType: (*BlogsAndPostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateABlog",
			Handler:    _BlogsAndPostService_CreateABlog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get100Blogs",
			Handler:       _BlogsAndPostService_Get100Blogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/blogsandposts_service/blog_service/pb/blogsandposts.proto",
}
