// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: services/blogsandposts_service/blog_service/pb/blogposts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBlogRequest_ContentOwnerShip int32

const (
	CreateBlogRequest_THE_USER    CreateBlogRequest_ContentOwnerShip = 0
	CreateBlogRequest_THE_MONKEYS CreateBlogRequest_ContentOwnerShip = 1
	CreateBlogRequest_THE_PARTNER CreateBlogRequest_ContentOwnerShip = 2
)

// Enum value maps for CreateBlogRequest_ContentOwnerShip.
var (
	CreateBlogRequest_ContentOwnerShip_name = map[int32]string{
		0: "THE_USER",
		1: "THE_MONKEYS",
		2: "THE_PARTNER",
	}
	CreateBlogRequest_ContentOwnerShip_value = map[string]int32{
		"THE_USER":    0,
		"THE_MONKEYS": 1,
		"THE_PARTNER": 2,
	}
)

func (x CreateBlogRequest_ContentOwnerShip) Enum() *CreateBlogRequest_ContentOwnerShip {
	p := new(CreateBlogRequest_ContentOwnerShip)
	*p = x
	return p
}

func (x CreateBlogRequest_ContentOwnerShip) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateBlogRequest_ContentOwnerShip) Descriptor() protoreflect.EnumDescriptor {
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_enumTypes[0].Descriptor()
}

func (CreateBlogRequest_ContentOwnerShip) Type() protoreflect.EnumType {
	return &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_enumTypes[0]
}

func (x CreateBlogRequest_ContentOwnerShip) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateBlogRequest_ContentOwnerShip.Descriptor instead.
func (CreateBlogRequest_ContentOwnerShip) EnumDescriptor() ([]byte, []int) {
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescGZIP(), []int{0, 0}
}

// CreateBlogRequest
type CreateBlogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string                             `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title            string                             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content          string                             `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Author           string                             `protobuf:"bytes,4,opt,name=Author,proto3" json:"Author,omitempty"`
	IsDraft          bool                               `protobuf:"varint,5,opt,name=isDraft,proto3" json:"isDraft,omitempty"`
	Tags             []string                           `protobuf:"bytes,6,rep,name=Tags,proto3" json:"Tags,omitempty"`
	CreateTime       *timestamppb.Timestamp             `protobuf:"bytes,7,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime       *timestamppb.Timestamp             `protobuf:"bytes,8,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	QuickRead        bool                               `protobuf:"varint,9,opt,name=quickRead,proto3" json:"quickRead,omitempty"`
	ContentOwnerShip CreateBlogRequest_ContentOwnerShip `protobuf:"varint,10,opt,name=contentOwnerShip,proto3,enum=Blog.CreateBlogRequest_ContentOwnerShip" json:"contentOwnerShip,omitempty"`
	CanEdit          bool                               `protobuf:"varint,11,opt,name=canEdit,proto3" json:"canEdit,omitempty"`
	AuthorEmail      string                             `protobuf:"bytes,12,opt,name=AuthorEmail,proto3" json:"AuthorEmail,omitempty"`
	FolderPath       string                             `protobuf:"bytes,13,opt,name=folderPath,proto3" json:"folderPath,omitempty"`
}

func (x *CreateBlogRequest) Reset() {
	*x = CreateBlogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogRequest) ProtoMessage() {}

func (x *CreateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBlogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateBlogRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateBlogRequest) GetIsDraft() bool {
	if x != nil {
		return x.IsDraft
	}
	return false
}

func (x *CreateBlogRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateBlogRequest) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *CreateBlogRequest) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *CreateBlogRequest) GetQuickRead() bool {
	if x != nil {
		return x.QuickRead
	}
	return false
}

func (x *CreateBlogRequest) GetContentOwnerShip() CreateBlogRequest_ContentOwnerShip {
	if x != nil {
		return x.ContentOwnerShip
	}
	return CreateBlogRequest_THE_USER
}

func (x *CreateBlogRequest) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *CreateBlogRequest) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *CreateBlogRequest) GetFolderPath() string {
	if x != nil {
		return x.FolderPath
	}
	return ""
}

type CreateBlogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id     string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateBlogResponse) Reset() {
	*x = CreateBlogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogResponse) ProtoMessage() {}

func (x *CreateBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogResponse.ProtoReflect.Descriptor instead.
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBlogResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateBlogResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateBlogResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBlogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBlogsRequest) Reset() {
	*x = GetBlogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsRequest) ProtoMessage() {}

func (x *GetBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsRequest.ProtoReflect.Descriptor instead.
func (*GetBlogsRequest) Descriptor() ([]byte, []int) {
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescGZIP(), []int{2}
}

type GetBlogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author      string                 `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	AuthorEmail string                 `protobuf:"bytes,4,opt,name=AuthorEmail,proto3" json:"AuthorEmail,omitempty"`
	CreateTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	QuickRead   bool                   `protobuf:"varint,6,opt,name=quickRead,proto3" json:"quickRead,omitempty"`
}

func (x *GetBlogsResponse) Reset() {
	*x = GetBlogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsResponse) ProtoMessage() {}

func (x *GetBlogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsResponse.ProtoReflect.Descriptor instead.
func (*GetBlogsResponse) Descriptor() ([]byte, []int) {
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlogsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBlogsResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetBlogsResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GetBlogsResponse) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *GetBlogsResponse) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *GetBlogsResponse) GetQuickRead() bool {
	if x != nil {
		return x.QuickRead
	}
	return false
}

type GetBlogByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetBlogByIdReq) Reset() {
	*x = GetBlogByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogByIdReq) ProtoMessage() {}

func (x *GetBlogByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogByIdReq.ProtoReflect.Descriptor instead.
func (*GetBlogByIdReq) Descriptor() ([]byte, []int) {
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlogByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBlogByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title      string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author     string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Content    string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	QuickRead  bool                   `protobuf:"varint,6,opt,name=quickRead,proto3" json:"quickRead,omitempty"`
	Tags       []string               `protobuf:"bytes,7,rep,name=Tags,proto3" json:"Tags,omitempty"`
}

func (x *GetBlogByIdResp) Reset() {
	*x = GetBlogByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogByIdResp) ProtoMessage() {}

func (x *GetBlogByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogByIdResp.ProtoReflect.Descriptor instead.
func (*GetBlogByIdResp) Descriptor() ([]byte, []int) {
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescGZIP(), []int{5}
}

func (x *GetBlogByIdResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBlogByIdResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetBlogByIdResp) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GetBlogByIdResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetBlogByIdResp) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *GetBlogByIdResp) GetQuickRead() bool {
	if x != nil {
		return x.QuickRead
	}
	return false
}

func (x *GetBlogByIdResp) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type EditBlogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title   string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Method  string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Tags    []string `protobuf:"bytes,5,rep,name=Tags,proto3" json:"Tags,omitempty"`
}

func (x *EditBlogReq) Reset() {
	*x = EditBlogReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditBlogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditBlogReq) ProtoMessage() {}

func (x *EditBlogReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditBlogReq.ProtoReflect.Descriptor instead.
func (*EditBlogReq) Descriptor() ([]byte, []int) {
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescGZIP(), []int{6}
}

func (x *EditBlogReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditBlogReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditBlogReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EditBlogReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *EditBlogReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type EditBlogRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id     string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EditBlogRes) Reset() {
	*x = EditBlogRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditBlogRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditBlogRes) ProtoMessage() {}

func (x *EditBlogRes) ProtoReflect() protoreflect.Message {
	mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditBlogRes.ProtoReflect.Descriptor instead.
func (*EditBlogRes) Descriptor() ([]byte, []int) {
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescGZIP(), []int{7}
}

func (x *EditBlogRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EditBlogRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EditBlogRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BlogId      string                 `protobuf:"bytes,2,opt,name=BlogId,proto3" json:"BlogId,omitempty"`
	UserId      string                 `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Comment     string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	CommentTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=commentTime,proto3" json:"commentTime,omitempty"`
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCommentReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateCommentReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *CreateCommentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCommentReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateCommentReq) GetCommentTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CommentTime
	}
	return nil
}

type CreateCommentRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlogId  string `protobuf:"bytes,1,opt,name=BlogId,proto3" json:"BlogId,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateCommentRes) Reset() {
	*x = CreateCommentRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRes) ProtoMessage() {}

func (x *CreateCommentRes) ProtoReflect() protoreflect.Message {
	mi := &file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRes.ProtoReflect.Descriptor instead.
func (*CreateCommentRes) Descriptor() ([]byte, []int) {
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCommentRes) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *CreateCommentRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCommentRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_services_blogsandposts_service_blog_service_pb_blogposts_proto protoreflect.FileDescriptor

var file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDesc = []byte{
	0x0a, 0x3e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x73,
	0x61, 0x6e, 0x64, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62,
	0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x42, 0x6c, 0x6f, 0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5, 0x04, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x44, 0x72, 0x61, 0x66, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x44, 0x72, 0x61, 0x66, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54,
	0x61, 0x67, 0x73, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x3a, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x71,
	0x75, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x61, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x71, 0x75, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x61, 0x64, 0x12, 0x54, 0x0a, 0x10, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x53, 0x68, 0x69, 0x70, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x53, 0x68, 0x69, 0x70, 0x52, 0x10, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x53, 0x68, 0x69, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x61, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x63, 0x61, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x66,
	0x6f, 0x6c, 0x64, 0x65, 0x72, 0x50, 0x61, 0x74, 0x68, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x50, 0x61, 0x74, 0x68, 0x22, 0x42, 0x0a, 0x10, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x53, 0x68, 0x69, 0x70, 0x12,
	0x0c, 0x0a, 0x08, 0x54, 0x48, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x54, 0x48, 0x45, 0x5f, 0x4d, 0x4f, 0x4e, 0x4b, 0x45, 0x59, 0x53, 0x10, 0x01, 0x12, 0x0f,
	0x0a, 0x0b, 0x54, 0x48, 0x45, 0x5f, 0x50, 0x41, 0x52, 0x54, 0x4e, 0x45, 0x52, 0x10, 0x02, 0x22,
	0x52, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xcc, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x6c,
	0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x3a, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x71, 0x75, 0x69, 0x63, 0x6b,
	0x52, 0x65, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x71, 0x75, 0x69, 0x63,
	0x6b, 0x52, 0x65, 0x61, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0xd7, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42,
	0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67,
	0x73, 0x22, 0x79, 0x0a, 0x0b, 0x45, 0x64, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x22, 0x4b, 0x0a, 0x0b,
	0x45, 0x64, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xaa, 0x01, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x42, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x42, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x5a, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x6c,
	0x6f, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x6c, 0x6f, 0x67,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0xc4, 0x02, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67,
	0x12, 0x17, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c,
	0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x42, 0x6c, 0x6f, 0x67,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67,
	0x73, 0x12, 0x15, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x3c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x42,
	0x79, 0x49, 0x64, 0x12, 0x14, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c,
	0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x42, 0x6c, 0x6f, 0x67,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x45, 0x64, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x12, 0x11,
	0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65,
	0x71, 0x1a, 0x11, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x42, 0x6c, 0x6f,
	0x67, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x2e, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x61, 0x6e, 0x64,
	0x70, 0x6f, 0x73, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x6c,
	0x6f, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescOnce sync.Once
	file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescData = file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDesc
)

func file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescGZIP() []byte {
	file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescOnce.Do(func() {
		file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescData)
	})
	return file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDescData
}

var file_services_blogsandposts_service_blog_service_pb_blogposts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_services_blogsandposts_service_blog_service_pb_blogposts_proto_goTypes = []interface{}{
	(CreateBlogRequest_ContentOwnerShip)(0), // 0: Blog.CreateBlogRequest.ContentOwnerShip
	(*CreateBlogRequest)(nil),               // 1: Blog.CreateBlogRequest
	(*CreateBlogResponse)(nil),              // 2: Blog.CreateBlogResponse
	(*GetBlogsRequest)(nil),                 // 3: Blog.GetBlogsRequest
	(*GetBlogsResponse)(nil),                // 4: Blog.GetBlogsResponse
	(*GetBlogByIdReq)(nil),                  // 5: Blog.GetBlogByIdReq
	(*GetBlogByIdResp)(nil),                 // 6: Blog.GetBlogByIdResp
	(*EditBlogReq)(nil),                     // 7: Blog.EditBlogReq
	(*EditBlogRes)(nil),                     // 8: Blog.EditBlogRes
	(*CreateCommentReq)(nil),                // 9: Blog.CreateCommentReq
	(*CreateCommentRes)(nil),                // 10: Blog.CreateCommentRes
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
}
var file_services_blogsandposts_service_blog_service_pb_blogposts_proto_depIdxs = []int32{
	11, // 0: Blog.CreateBlogRequest.createTime:type_name -> google.protobuf.Timestamp
	11, // 1: Blog.CreateBlogRequest.updateTime:type_name -> google.protobuf.Timestamp
	0,  // 2: Blog.CreateBlogRequest.contentOwnerShip:type_name -> Blog.CreateBlogRequest.ContentOwnerShip
	11, // 3: Blog.GetBlogsResponse.createTime:type_name -> google.protobuf.Timestamp
	11, // 4: Blog.GetBlogByIdResp.createTime:type_name -> google.protobuf.Timestamp
	11, // 5: Blog.CreateCommentReq.commentTime:type_name -> google.protobuf.Timestamp
	1,  // 6: Blog.BlogService.CreateBlog:input_type -> Blog.CreateBlogRequest
	3,  // 7: Blog.BlogService.GetBlogs:input_type -> Blog.GetBlogsRequest
	5,  // 8: Blog.BlogService.GetBlogById:input_type -> Blog.GetBlogByIdReq
	7,  // 9: Blog.BlogService.EditBlog:input_type -> Blog.EditBlogReq
	9,  // 10: Blog.BlogService.CreateComment:input_type -> Blog.CreateCommentReq
	2,  // 11: Blog.BlogService.CreateBlog:output_type -> Blog.CreateBlogResponse
	4,  // 12: Blog.BlogService.GetBlogs:output_type -> Blog.GetBlogsResponse
	6,  // 13: Blog.BlogService.GetBlogById:output_type -> Blog.GetBlogByIdResp
	8,  // 14: Blog.BlogService.EditBlog:output_type -> Blog.EditBlogRes
	10, // 15: Blog.BlogService.CreateComment:output_type -> Blog.CreateCommentRes
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_services_blogsandposts_service_blog_service_pb_blogposts_proto_init() }
func file_services_blogsandposts_service_blog_service_pb_blogposts_proto_init() {
	if File_services_blogsandposts_service_blog_service_pb_blogposts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBlogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBlogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditBlogReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditBlogRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_blogsandposts_service_blog_service_pb_blogposts_proto_goTypes,
		DependencyIndexes: file_services_blogsandposts_service_blog_service_pb_blogposts_proto_depIdxs,
		EnumInfos:         file_services_blogsandposts_service_blog_service_pb_blogposts_proto_enumTypes,
		MessageInfos:      file_services_blogsandposts_service_blog_service_pb_blogposts_proto_msgTypes,
	}.Build()
	File_services_blogsandposts_service_blog_service_pb_blogposts_proto = out.File
	file_services_blogsandposts_service_blog_service_pb_blogposts_proto_rawDesc = nil
	file_services_blogsandposts_service_blog_service_pb_blogposts_proto_goTypes = nil
	file_services_blogsandposts_service_blog_service_pb_blogposts_proto_depIdxs = nil
}
